services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}Redis:/data
    depends_on:
      - resolver
    dns:
      - ${MAILU_RESOLVER_IP}

  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - ${MAILU_WEB_IP}:${MAILU_PORT_HTTP}:80
      - ${MAILU_WEB_IP}:${MAILU_PORT_HTTPS}:443
      - ${MAILU_SERVICE_IP}:25:25
      - ${MAILU_SERVICE_IP}:465:465
      - ${MAILU_SERVICE_IP}:587:587
      - ${MAILU_SERVICE_IP}:110:110
      - ${MAILU_SERVICE_IP}:995:995
      - ${MAILU_SERVICE_IP}:143:143
      - ${MAILU_SERVICE_IP}:993:993
      - ${MAILU_SERVICE_IP}:4190:4190
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}SSL:/certs
      - ${MAILU_SERVICE_VOLUME_PATH}Override/NginX:/overrides:ro
    depends_on:
      - redis
    dns:
      - ${MAILU_RESOLVER_IP}

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: ${MAILU_RESOLVER_IP}

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}Data:/data
      - ${MAILU_SERVICE_VOLUME_PATH}DKIM:/dkim
    depends_on:
      - redis
    dns:
      - ${MAILU_RESOLVER_IP}

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}Mail:/mail
      - ${MAILU_SERVICE_VOLUME_PATH}Override/DoveCot:/overrides:ro
    depends_on:
      - front
    dns:
      - ${MAILU_RESOLVER_IP}

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}Queue:/queue
      - ${MAILU_SERVICE_VOLUME_PATH}Override/Postfix:/overrides:ro
    depends_on:
      - front
    dns:
      - ${MAILU_RESOLVER_IP}

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    depends_on:
      - resolver
    dns:
      - ${MAILU_RESOLVER_IP}

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}Filter:/var/lib/rspamd
      - ${MAILU_SERVICE_VOLUME_PATH}Override/RSpamD:/overrides:ro
    depends_on:
      - front
      - oletools
      - antivirus
    dns:
      - ${MAILU_RESOLVER_IP}

  antivirus:
    image: clamav/clamav-debian:1.4
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-antivirus
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}ClamAV:/var/lib/clamav
    healthcheck:
      test: ["CMD-SHELL", "kill -0 `cat /tmp/clamd.pid` && kill -0 `cat /tmp/freshclam.pid`"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2024.06}
    restart: always
    logging:
      driver: journald
      options:
        tag: mailu-webdav
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}DAV:/data

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-fetchmail
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}Data/Fetch:/data
    depends_on:
      - admin
      - smtp
      - imap
    dns:
      - ${MAILU_RESOLVER_IP}

  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - ${MAILU_SERVICE_VOLUME_PATH}WebMail:/data
      - ${MAILU_SERVICE_VOLUME_PATH}Override/RoundCube:/overrides:ro
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}
